trigger:
- main

variables:
  TF_ROOT: "Terraform"
  API_CERT_PASSWORD: "F5lab2023*"
  VES_P12_PASSWORD: "F5lab2023*"

pool:
  name: o-alasmar-windows-image

stages:
# -------------------
# Stage 1: Init
# -------------------
- stage: Init
  jobs:
  - job: TerraformInit
    steps:
    - script: |
        echo "Now entering TF_ROOT"
        export VES_P12_PASSWORD=$(VES_P12_PASSWORD)
        cd "$BUILD_SOURCESDIRECTORY/$TF_ROOT"
        terraform init
      displayName: 'Terraform Init '


# -------------------
# Stage 2: Plan&Apply
# -------------------
- stage: Apply
  jobs:
  - job: TerraformPlanApply
    steps:
    - script: |
        echo "Setting VES_P12_PASSWORD env var"
        export VES_P12_PASSWORD=$(VES_P12_PASSWORD)
        cd "$(Build.SourcesDirectory)/$(TF_ROOT)"
        terraform init
        terraform plan
        terraform apply -auto-approve
      displayName: 'Terraform Apply'
