trigger:
- main

variables:
  TF_ROOT: "terraform"
  TF_VAR_api_p12_file: "$(Build.SourcesDirectory)/${TF_ROOT}/credentials/xc-api-cert.p12"
  TF_VAR_url: "https://<tenant_name>.console.ves.volterra.io/api"
  API_CERT_PASSWORD: $(apiCertPassword)

stages:
- stage: Init
  jobs:
  - job: Init
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: 'Install Terraform 1.5.7'
    - script: |
        curl -L -o terraform-provider-volterra.zip https://github.com/f5devcentral/terraform-provider-volterra/releases/latest/download/terraform-provider-volterra-linux-amd64.zip
        mkdir -p ~/.terraform.d/plugins
        unzip terraform-provider-volterra.zip -d ~/.terraform.d/plugins
        chmod +x ~/.terraform.d/plugins/terraform-provider-volterra
      displayName: 'Install Volterra Provider'
    - script: |
        cd $(Build.SourcesDirectory)/${TF_ROOT}
        terraform init
      displayName: 'Terraform Init'

- stage: Plan
  jobs:
  - job: Plan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: 'Install Terraform 1.5.7'
    - script: |
        curl -L -o terraform-provider-volterra.zip https://github.com/f5devcentral/terraform-provider-volterra/releases/latest/download/terraform-provider-volterra-linux-amd64.zip
        mkdir -p ~/.terraform.d/plugins
        unzip terraform-provider-volterra.zip -d ~/.terraform.d/plugins
        chmod +x ~/.terraform.d/plugins/terraform-provider-volterra
      displayName: 'Install Volterra Provider'
    - script: |
        cd $(Build.SourcesDirectory)/${TF_ROOT}
        terraform plan -var="api_cert_password=$(API_CERT_PASSWORD)"
      displayName: 'Terraform Plan'

- stage: Apply
  jobs:
  - job: Apply
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: 'Install Terraform 1.5.7'
    - script: |
        curl -L -o terraform-provider-volterra.zip https://github.com/f5devcentral/terraform-provider-volterra/releases/latest/download/terraform-provider-volterra-linux-amd64.zip
        mkdir -p ~/.terraform.d/plugins
        unzip terraform-provider-volterra.zip -d ~/.terraform.d/plugins
        chmod +x ~/.terraform.d/plugins/terraform-provider-volterra
      displayName: 'Install Volterra Provider'
    - script: |
        cd $(Build.SourcesDirectory)/${TF_ROOT}
        terraform apply -auto-approve -var="api_cert_password=$(API_CERT_PASSWORD)"
      displayName: 'Terraform Apply'
