trigger:
- main

variables:
  TF_ROOT: "terraform"
  API_CERT_PASSWORD: "F5lab2023*"
  VES_P12_PASSWORD: "F5lab2023*"

pool:
  name: o-alasmar-windows-image

stages:
# -------------------
# Stage 1: Init
# -------------------
- stage: Init
  jobs:
  - job: TerraformInit
    steps:
    - script: |
        echo Setting VES_P12_PASSWORD env var
        set VES_P12_PASSWORD=%VES_P12_PASSWORD%
        cd %BUILD_SOURCESDIRECTORY%\%TF_ROOT%
        terraform init
      displayName: 'Terraform Init'
      shell: cmd

# -------------------
# Stage 2: Plan
# -------------------
- stage: Plan
  dependsOn: Init
  jobs:
  - job: TerraformPlan
    steps:
    - script: |
        echo Setting VES_P12_PASSWORD env var
        set VES_P12_PASSWORD=%VES_P12_PASSWORD%
        cd %BUILD_SOURCESDIRECTORY%\%TF_ROOT%
        terraform plan -var="api_cert_password=%API_CERT_PASSWORD%"
      displayName: 'Terraform Plan'
      shell: cmd

# -------------------
# Stage 3: Apply
# -------------------
- stage: Apply
  dependsOn: Plan
  jobs:
  - job: TerraformApply
    steps:
    - script: |
        echo Setting VES_P12_PASSWORD env var
        set VES_P12_PASSWORD=%VES_P12_PASSWORD%
        cd %BUILD_SOURCESDIRECTORY%\%TF_ROOT%
        terraform apply -auto-approve -var="api_cert_password=%API_CERT_PASSWORD%"
      displayName: 'Terraform Apply'
      shell: cmd
