trigger:
- main

variables:
  TF_ROOT: "terraform"
  API_CERT_PASSWORD: $(apiCertPassword)

pool:
  name: o-alasmar-windows-image

stages:
# -------------------
# Stage 1: Init
# -------------------
- stage: Init
  jobs:
  - job: TerraformInit
    steps:
    - script: |
        cd $(Build.SourcesDirectory)/${TF_ROOT}
        terraform init
      displayName: 'Terraform Init'

# -------------------
# Stage 2: Plan
# -------------------
- stage: Plan
  dependsOn: Init
  jobs:
  - job: TerraformPlan
    steps:
    - script: |
        cd $(Build.SourcesDirectory)/${TF_ROOT}
        terraform plan -var="api_cert_password=$(API_CERT_PASSWORD)"
      displayName: 'Terraform Plan'

# -------------------
# Stage 3: Apply
# -------------------
- stage: Apply
  dependsOn: Plan
  jobs:
  - job: TerraformApply
    steps:
    - script: |
        cd $(Build.SourcesDirectory)/${TF_ROOT}
        terraform apply -auto-approve -var="api_cert_password=$(API_CERT_PASSWORD)"
      displayName: 'Terraform Apply'
