trigger:
- main

variables:
  TF_ROOT: "Terraform"
  #TF_path: "MulitipleLB"
  TF_STATE_DIR: "/home/azureuser/infra/terraform-state"
  API_CERT_PASSWORD: "F5lab2023*"
  VES_P12_PASSWORD: "F5lab2023*"

pool:
  name: o-alasmar-windows-image

stages:
# -------------------
# Stage 1: Init
# -------------------
- stage: Init
  displayName: 'Terraform Init'
  jobs:
  - job: TerraformInit
    displayName: 'Init Job'
    steps:
    - script: |
        echo "Creating local Terraform state directory..."
        mkdir -p "$TF_STATE_DIR"

        echo "Running terraform init..."
        export VES_P12_PASSWORD="${VES_P12_PASSWORD}"
        cd "$BUILD_SOURCESDIRECTORY/$TF_ROOT"
        terraform init
      displayName: 'Terraform Init'

# -------------------
# Stage 2: Plan & Apply
# -------------------
- stage: Apply
  displayName: 'Terraform Plan and Apply'
  dependsOn: Init
  jobs:
  - job: TerraformPlanApply
    displayName: 'Plan & Apply Job'
    steps:
    - script: |
        echo "Running terraform plan and apply with custom local state..."
        export VES_P12_PASSWORD="${VES_P12_PASSWORD}"
        cd "$BUILD_SOURCESDIRECTORY/$TF_ROOT"

        terraform init
        terraform plan -state="$TF_STATE_DIR/terraform.tfstate" -out=tfplan
        terraform apply -state="$TF_STATE_DIR/terraform.tfstate" -auto-approve tfplan
      displayName: 'Terraform Plan & Apply'
